lua: build: link against liblua
ldd reports many errors regarding missing symbols because the library
is not linked against liblua.

root@openwrt ~ # ldd /usr/lib/lua/uci.so
        ldd (0x7f97830000)
        libuci.so.20250120 => /lib/libuci.so.20250120 (0x7f978bc000)
        libubox.so.20260213 => /lib/libubox.so.20260213 (0x7f9781e000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f977ed000)
        libc.so => ldd (0x7f97830000)
Error relocating /usr/lib/lua/uci.so: lua_objlen: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_pcall: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_getfield: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_gettop: symbol not found
Error relocating /usr/lib/lua/uci.so: luaL_checkstack: symbol not found
Error relocating /usr/lib/lua/uci.so: luaL_checklstring: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_setfield: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_isstring: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_pushvalue: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_pushnil: symbol not found
Error relocating /usr/lib/lua/uci.so: luaL_error: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_settop: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_pushcclosure: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_tolstring: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_type: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_pushboolean: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_settable: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_setmetatable: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_rawseti: symbol not found
Error relocating /usr/lib/lua/uci.so: luaL_newmetatable: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_newuserdata: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_error: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_pushstring: symbol not found
Error relocating /usr/lib/lua/uci.so: luaL_checkudata: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_rawgeti: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_toboolean: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_isuserdata: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_createtable: symbol not found
Error relocating /usr/lib/lua/uci.so: lua_pushinteger: symbol not found
root@openwrt ~ #

We have to link the lua uci library against liblua.

Signed-off-by: Martin Schiller <ms@dev.tdt.de>